### ISSUE TITLE
Invalid arguments on D3 Components

### ISSUE THREAD

**Issue by buriedsignals** [idyll-lang/idyll#680] opened 2021-01-18 13:57 UTC
Hey Matt! 

Making good headway and loving Idyll so far. Issuing a bug report as seeing the same error in two scenarios (still not familiar enough with the framework to debug it although I will keep trying), which is preventing me from continuing:

**Scenarios :**
1) after following the steps to create a no-template blog post within a multipage template, when launching the server (from within the post directory)
2) copy/pasting your [D3 component](https://idyll-lang.github.io/idyll-d3-component/), if I call the component in index.idyll

Throwing this error log
> [Idyll] Serving files from: /Users/buriedsignals/Code/buriedsignals/docs/
> node:internal/fs/utils:634
>     throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
> TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined

Just in case, my repository is public [here](https://github.com/buriedsignals/buriedsignals)

Thanks so much in advance!

**Comment by buriedsignals** [comment] 2021-01-19 09:30
Fixed if I remove the CustomD3 component, should be completely fixed if I add a .toString() function (will let you know). For now as a heads up if other users are experiencing the issue, prevents me from launching the server and following the steps listed in the documentation on a new blog post. Cheers!

**Comment by buriedsignals** [comment] 2021-01-22 11:01
Hey Matt,

I've been running into a wall on this one :( It looks like it is expecting a div component but is getting undefined?

**Comment by mathisonian** [comment] 2021-01-23 00:42
@buriedsignals I was able to get the post in your example repo to compile locally with the following changes: https://github.com/mathisonian/buriedsignals/commit/24885fdb557539a456daf0b7673c0bb6150556ed

Does that have any effect for you? Steps to test:

- clone [my forked version](https://github.com/mathisonian/buriedsignals/commit/24885fdb557539a456daf0b7673c0bb6150556ed) of the repo
- cd into the repo folder and run `npm install`
- cd into the `posts/d3test` folder and run `idyll`

**Comment by buriedsignals** [comment] 2021-01-23 07:35
Hey @mathisonian unfortunately still getting the same error. I cloned your version of the repo into a new repository and started fresh to be safe. I also tried creating an article separately and ran into the same error :( At the moment I'm unable tu use Idyll essentially. I did get the blog index / pages up and running on Jekyll last night though, keen to start testing the iframe and begin working on the first article as soon as I can!

**Comment by buriedsignals** [comment] 2021-01-23 07:55
I recorded this, just in case. At the end I get my usual error on installing dependencies, which is fixed if I manually change the react version in package.json and run `yarn install`. I then get the invalid arguments error, fixed when removing the D3 Component. 

Not sure what other information I can provide, happy to help any way I can and apologies for the complication here. https://www.loom.com/share/2a371f577b8a492bae2cf9d2f4721af8

**Comment by mathisonian** [comment] 2021-01-25 03:23
Thanks for the recording @buriedsignals this should be super helpful for debugging. It might take me some time this week to dig into this one... 

Could you confirm that if you replace the custom D3 component with a custom React component (e.g. something like https://github.com/idyll-lang/idyll/blob/master/packages/idyll-template-projects/templates/article/components/custom-component.js) the project compiles correctly? I'd like to narrow this down to confirm that the D3 component is actually the root cause here and not something else

**Comment by buriedsignals** [comment] 2021-01-25 08:58
I understand and thank you so much @mathisonian. I am getting the same error when extending it as a React component, glad you asked! 

`The "path" argument must be of type string or an instance of Buffer or URL. Received undefined`

Please let me know if there is anything I can do.

**Comment by mathisonian** [comment] 2021-03-28 21:56
This was fixed by #719. Thanks again for reporting and helping debug @buriedsignals. With this latest fix we are back to being compatible with all recent node versions.

**Closed by mathisonian** 2021-03-28 21:56 UTC
Labels: Compiler, bug
