### ISSUE TITLE
Idyll replaces an equation with a duplicate

### ISSUE THREAD

**Issue by suhr** [idyll-lang/idyll#566] opened 2019-07-16 23:07 UTC
The index.idyll: https://gist.github.com/suhr/ad0d710c8f2f02fe710fe31598d5b4db

Idyll output: ![2019-07-17-020052_1920x1080_scrot](https://user-images.githubusercontent.com/65870/61335745-4d983880-a837-11e9-9008-cea502a8bffb.png)

Expected output: the third equation should be `x = x`.

Tried: `idyll clean` and removing the `build` dir, using a different browser.

**Comment by mathisonian** [comment] 2019-07-16 23:16
This appears to be a bug with how the client-side runtime is interpreting the initial AST and HTML that the compilation process sends to the browser. 

I've noticed that if you run with server-side rendering turned off (`idyll --no-ssr`) the issue disappears. This indicates that the issue is likely in the `idyll-document` package which is loaded in the client.

**Comment by mathisonian** [comment] 2019-07-17 01:22
Fixed in https://github.com/idyll-lang/idyll/pull/567

**Closed by mathisonian** 2019-07-17 01:22 UTC
Labels: Runtime, bug

**Comment by mathisonian** [comment] 2019-07-17 01:25
I just published a new release, the fix is available in `idyll@4.6.0`.
