### ISSUE TITLE
Dependencies issue

### ISSUE THREAD

**Issue by buriedsignals** [idyll-lang/idyll#679] opened 2021-01-15 15:10 UTC
Hi Idyll!

I was unable to install the Idyll package using the npm command, I receive this error log (screenshot also attached) :

npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@16.14.0
npm WARN node_modules/idyll/node_modules/react
npm WARN   react@"^16.0.0" from idyll@5.0.2
npm WARN   node_modules/idyll
npm WARN     idyll@"*" from the root project
npm WARN   9 more (idyll-components, react-dom, idyll-document, ...)
Could not resolve dependency:
npm WARN peer react@">=^16.0.0" from react-tooltip@3.11.6
npm WARN node_modules/idyll/node_modules/react-tooltip
npm WARN   react-tooltip@"^3.8.4" from idyll-document@3.2.5

I successfully installed the package using yarn, however when I create a multipage project I get an error message "Could not install Idyll dependencies." Screenshot also attached. 

I'm running React 17.0.1 on OSX 10.15.17, should I be downgrading to install the library?

Thank you!
T
 
![Screenshot 2021-01-15 at 16 03 51](https://user-images.githubusercontent.com/34089393/104743481-0a7c9580-574c-11eb-93e0-57abd3a4a812.png)
![Screenshot 2021-01-15 at 16 05 41](https://user-images.githubusercontent.com/34089393/104743491-0badc280-574c-11eb-8b09-0c6f6d0a1d9e.png)

**Comment by mathisonian** [comment] 2021-01-15 16:43
Hey @buriedsignals 👋 

It looks like this might be two separate issues...

On the `npm` side, I'm guessing what happened is that you already have a copy of `react@17` globally installed and so things are unhappy when v16 isn't available? The most straightforward fix for this is probably for us to loosen the version requirement there and allow v17 as well, though I think we'll have to make a couple minor changes to get that to work (in the meantime I expect downgrading [or removing] your global copy of react would solve it). 

On the `yarn` side I'm not so sure... is there any additional error output? Once you start installing dependencies _in a specific project_ it should be able to safely ignore any globally installed versions of things that you have and just work with the local copy, I wouldn't expect the global react 16/17 issue to affect installation once `idyll` itself was successfully available

**Comment by buriedsignals** [comment] 2021-01-15 20:56
Hey Matt,

Alright, I hit the wall for about an hour or two trying to remove npm and node_modules entirely, re-installing and still getting the same error log (could not for the life of me install a version below 16.4.0). Glad I focused on yarn instead :)

BUT I went for the following process and got it to work : 
1) install idyll globally with yarn, (unable to install dependencies)
2) create the multipage project 
3) manually added react 16.0.0 to the package.json, which force installed it in the directory
4) got the server to run, ready to rumble

Thanks!

**Comment by mathisonian** [comment] 2021-01-15 21:18
Alright, I'm glad you got something that's working for the time being. For debugging / reproduction purposes could you share which version nodejs and npm you have installed? 

The output of: 
```
$ node --version 
$ npm --version
```

**Comment by buriedsignals** [comment] 2021-01-15 23:02
Of course! Here they are :

npm --version                                               
7.4.0
node --version
v15.6.

**Closed** 2021-01-17 08:27 UTC
